### ISSUE TITLE
Add new work type Audio

### ISSUE THREAD

**Issue by jamesmooneybodleian** [RepoCamp/teapot#1]
STORY
I would like to add an audio work type with some additional metadata.

Metadata
Audio
	Title (title)
	Description (descriotion)
	Genre
	Creator (creator)
	Publisher (Publisher)
	License (License)
	Language (Language)

ACCEPTANCE
The repository provides me with the option to create an audio work type and allow new metadata fields (see above).

**Comment by drschoener** [comment]
The file being uploaded should be really a .wav, .ogg or the like, not just anything

**Comment by jamesmooneybodleian** [comment]
This has proved to be too difficult for the remaining time.
