### ISSUE TITLE
 License should be a required field

### ISSUE THREAD

**Issue by drschoener** [RepoCamp/teapot#4]
STORY
As a repository administrator, I would like to require depositors to specify the licensing type they wish to make their content available under, so that I can have the repository display appropriate licensing information when other users access the work.

ACCEPTANCE

    License should display without having to click the 'additional fields' button
    License should be a required field
    License should appear after the Rights Statement on the input form
    Owner should appear after the License on the input form

**Comment by jamesmooneybodleian** [comment]
License is part of Hyrax::BasicMetadata
